// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shsvqcfuwlqzlofcnaul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoc3ZxY2Z1d2xxemxvZmNuYXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMDgwMDksImV4cCI6MjA2NjU4NDAwOX0.x4NYQGWiY5ccJmDFdRL2B3ZTDqx9gjEMDi_TXVmZNJk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);